version: '3'

tasks:
  build-mac:
    desc: Build the app
    cmds:
      - go build -o forge main.go

  build-linux:
    desc: Build the app for linux
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o bin/forge main.go

  build-windows:
    desc: Build the app for windows
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o forge.exe main.go

  bin-mac:
    desc: Adds to user bin to use anywhere on the computer in terminal
    cmds:
      - sudo mv forge /usr/local/bin

  bin-linux:
    desc: Adds to user bin to use anywhere on the computer in terminal
    cmds:
      - sudo mv bin/forge /usr/local/bin

  bin-windows:
    desc: Adds to Windows/System32 to use anywhere on the computer in terminal
    cmds:
      - Move-Item .\forge.exe C:\Windows\System32\

  zsh-ac:
    desc: Creates zsh auto completion file
    cmds:
      - forge completion zsh > zsh.txt
      
  pwsh-ac:
    desc: Creates powershell auto completion file
    cmds:
      - forge completion powershell > pwsh.txt